version: '3'

services:
  logicircle:
    build: .
    env_file:
      - .env
    volumes:
      - "./Downloads:/usr/src/app/Downloads"
     # - "/Volumes/logicircle-backup:/usr/src/app/network_drive"
    restart: unless-stopped
